# This workflow will build the extension against the latest Liquibase artifact
name: "Nightly build"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1-5"

permissions:
  contents: read
  pull-requests: write
  packages: read
  id-token: write # Required for OIDC authentication

jobs:
  nightly-build:
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@main
    with:
      nightly: true
    secrets: inherit

  mongo-atlas-tests:
    name: MongoDB Atlas 8 Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Configure AWS credentials for vault access
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Get secrets from vault
        id: vault-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@2cb1a461cbd4865ac4299648312e4704c646cd53 # v3.0.1
        with:
          secret-ids: |
            ,/vault/liquibase
          parse-json-secrets: true

      - name: Harness Foundational Test Suite Run on Atlas 8
        run: mvn -Dtest="HarnessNoSqlCompatibility" -DconfigFile=/harness-config-cloud.yml  -DdbName=mongodb -DdbUsername=${{env.TH_DB_ADMIN}} -DdbPassword=${{env.TH_DB_PASSWD}} -DdbUrl='${{env.TH_MONGO_ATLAS_URL}}' clean package

      - name: Archive Mongo Atlas Test Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: mongodb-test-results
          path: build/spock-reports
